### ISSUE TITLE
Add support for pdf-tools

### ISSUE THREAD

**Issue by tuhdo** [skeeto/x86-lookup#1]
PDF tools is an excellent PDF reader for Emacs: https://github.com/politza/pdf-tools

I have this configuration for using `pdf-view-mode` to open a page:

``` elisp
(defun x86-lookup-browse-pdf-view-emacs (pdf page)
          "View PDF at PAGE using Emacs' `pdf-view-mode' and `display-buffer'."
          (with-selected-window (display-buffer (find-file-noselect pdf :nowarn))
            (pdf-view-goto-page page)))

(setq x86-lookup-browse-pdf-function 'x86-lookup-browse-pdf-view-emacs)
```

It would be nice if `x86-lookup` supports `pdf-tools`. You should give it a try. It's really fast at opening PDF.

**Comment by tuhdo** [comment]
On a side note: you should suggest people to download volumn 2, since it's smaller than other manuals and contains the actual instruction list that `x86-lookup` can retrieve.

**Comment by skeeto** [comment]
Does this do it correctly? I'm looking for a function I can drop into x86-lookup without creating a dependency.

``` el
(defun x86-lookup-browse-pdf-pdf-tools (pdf page)
  "View PDF at PAGE using Emacs' `pdf-view-mode' and `display-buffer'."
  (require 'pdf-tools)
  (with-selected-window (display-buffer (find-file-noselect pdf :nowarn))
    (with-no-warnings
      (pdf-view-goto-page page))))
```

**Comment by tuhdo** [comment]
I think `x86-lookup` should automatically uses `pdf-view-mode` when it's available and `doc-view-mode` otherwise. Like this:

``` elisp
(defun x86-lookup-browse-pdf-emacs (pdf page)
  "View PDF at PAGE using Emacs' `doc-view-mode' and `display-buffer'."
  (if (package-installed-p 'pdf-tools)
      (with-selected-window (display-buffer (find-file-noselect pdf :nowarn))
        (pdf-view-goto-page page))
    (if (doc-view-mode-p 'pdf)
        (with-selected-window (display-buffer (find-file-noselect pdf :nowarn))
          (doc-view-goto-page page))
      (error "doc-view not available for PDF"))))
```

**Comment by skeeto** [comment]
Since x86-lookup-browse-pdf-any tries one after another, there's no
reason to put both in the same function. What do you think of 8f17cd2?

The `require` is because pdf-view-goto-page isn't autoloaded (though I
guess opening the PDF would do that anyway), and it will result in an
immediate error (i.e. before the PDF is opened) if it's not installed.
The with-no-warnings is necessary so that Emacs won't complain when it
byte-compiles the file.

**Comment by tuhdo** [comment]
The reason I want `x86-lookup-browse-pdf-any` to use `pdf-view-mode` is for convenience: users open the PDF in Emacs anyway, so we should use a much better package for reading PDF right inside Emacs.

As for the `require`, I am using `use-package`, so I didn't notice that :)

Thanks for the update, anyway.
