### ISSUE TITLE
Can generate index for PDF

### ISSUE THREAD

**Issue by stardiviner** [skeeto/x86-lookup#3]
I got the following error when I run command `x86-lookup`. It generate index:

```
apply: ‘recenter'ing a window that does not display current-buffer.
```

I run `edebug` on function `x86-lookup-create-index`. And found The problem is on function: `x86-lookup-create-index`'s `forward-page`.

**Comment by skeeto** [comment]
What version of pdftotext (pdftotext -v) and Emacs are you using? It
looks like you're running a development version Emacs 25, but I'm unable
to reproduce the issue in a default instance of Emacs 25. The error
you're seeing only appears in Emacs 25, from a check added in Emacs
commit 3da983f.

Running edebug was really helpful. I'm guessing that you have a package
hooking forward-page, either directly or indirectly, and it's invoking
recenter (in window.c) when it shouldn't. There's nothing in
forward-page that suggests it should invoke recenter.

**Comment by stardiviner** [comment]
I searched over my init files. And I did find the advice on `forward-page`.

``` lisp
(advice-add 'forward-page :after #'recenter)
```

This problem is solved.
